-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  action text NOT NULL CHECK (action = ANY (ARRAY['subscription_deletion'::text, 'subscription_creation'::text, 'subscription_modification'::text, 'user_modification'::text, 'bulk_operation'::text, 'selection_window_closure'::text, 'queue_order_creation'::text, 'order_creation'::text, 'selection_window_opened'::text, 'selection_window_closed'::text, 'system_operation'::text])),
  resource_type text NOT NULL,
  resource_id uuid NOT NULL,
  user_id uuid,
  admin_user_id uuid,
  action_details jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT admin_audit_logs_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.admin_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  request_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_requests_pkey PRIMARY KEY (id),
  CONSTRAINT admin_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL UNIQUE,
  setting_value text,
  is_encrypted boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_users_view (
  id uuid NOT NULL,
  email text,
  phone text NOT NULL,
  first_name text,
  last_name text,
  role USER-DEFINED NOT NULL DEFAULT 'user'::app_role,
  created_at timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  city text,
  state text,
  address_line1 text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_users_view_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL,
  old_values jsonb,
  new_values jsonb,
  changed_by uuid,
  changed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.billing_adjustments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['credit'::text, 'debit'::text, 'refund'::text, 'discount'::text])),
  amount numeric NOT NULL,
  reason text NOT NULL,
  reference_id text,
  effective_date timestamp with time zone NOT NULL,
  notes text,
  performed_by text NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT billing_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT billing_adjustments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.billing_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid NOT NULL,
  amount numeric NOT NULL,
  gst numeric NOT NULL,
  total_amount numeric NOT NULL,
  billing_date timestamp with time zone NOT NULL DEFAULT now(),
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  payment_id text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_records_pkey PRIMARY KEY (id),
  CONSTRAINT billing_records_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.campaign_offer_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  offer_id uuid NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT campaign_offer_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_offer_assignments_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.promotional_campaigns(id),
  CONSTRAINT campaign_offer_assignments_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.promotional_offers(id)
);
CREATE TABLE public.carousel_slides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  subtitle text NOT NULL,
  button_text text NOT NULL,
  button_link text NOT NULL,
  image_url text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT carousel_slides_pkey PRIMARY KEY (id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.custom_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone text UNIQUE,
  email text UNIQUE,
  first_name text,
  last_name text,
  phone_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone,
  is_active boolean DEFAULT true,
  role USER-DEFINED NOT NULL DEFAULT 'user'::app_role,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip_code text,
  avatar_url text,
  latitude numeric,
  longitude numeric,
  subscription_plan USER-DEFINED,
  subscription_active boolean,
  subscription_end_date timestamp with time zone,
  pickup_day character varying,
  signup_token text,
  fcm_token text,
  CONSTRAINT custom_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.custom_users_phone_backup (
  id uuid,
  phone text,
  created_at timestamp with time zone
);
CREATE TABLE public.custom_users_phone_backup_2025_07_05_02_08_38 (
  id uuid,
  phone text,
  new_phone text
);
CREATE TABLE public.customer_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  address_type text DEFAULT 'home'::text CHECK (address_type = ANY (ARRAY['home'::text, 'work'::text, 'other'::text])),
  is_default boolean DEFAULT false,
  first_name text,
  last_name text,
  phone text,
  email text,
  address_line_1 text NOT NULL,
  address_line_2 text,
  landmark text,
  city text NOT NULL,
  state text NOT NULL,
  country text NOT NULL DEFAULT 'India'::text,
  postal_code text,
  latitude numeric,
  longitude numeric,
  plus_code text,
  delivery_instructions text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_addresses_pkey PRIMARY KEY (id),
  CONSTRAINT customer_addresses_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.customer_drops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id text NOT NULL,
  drop_step text NOT NULL,
  drop_reason text,
  flow_type text NOT NULL,
  plan_id text,
  age_group text,
  selected_toys_count integer DEFAULT 0,
  total_amount numeric,
  user_agent text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  device_type text,
  browser text,
  os text,
  country text,
  city text,
  time_on_page_seconds integer,
  interactions_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_drops_pkey PRIMARY KEY (id),
  CONSTRAINT customer_drops_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.customer_subscription_status (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  current_subscription_id uuid,
  is_new_customer boolean DEFAULT true,
  first_order_date date,
  total_completed_cycles integer DEFAULT 0,
  toys_in_possession jsonb DEFAULT '[]'::jsonb,
  toys_in_possession_count integer DEFAULT 0,
  last_delivery_date date,
  next_pickup_due_date date,
  current_cycle_number integer DEFAULT 1,
  subscription_cycle_day integer DEFAULT 1,
  cycle_start_date date,
  cycle_end_date date,
  primary_pincode character varying,
  assigned_pickup_day character varying,
  assigned_delivery_day character varying,
  is_active boolean DEFAULT true,
  requires_pickup boolean DEFAULT false,
  next_action_type character varying DEFAULT 'delivery'::character varying CHECK (next_action_type::text = ANY (ARRAY['delivery'::character varying, 'pickup'::character varying, 'pickup_and_delivery'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_subscription_status_pkey PRIMARY KEY (id),
  CONSTRAINT customer_subscription_status_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT customer_subscription_status_current_subscription_id_fkey FOREIGN KEY (current_subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.customer_uuid_mapping (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  current_user_uuid uuid,
  migration_customer_id character varying,
  match_type character varying,
  match_confidence character varying,
  phone_normalized character varying,
  email_matched character varying,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  verified_at timestamp without time zone,
  CONSTRAINT customer_uuid_mapping_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dispatch_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dispatch_order_id uuid NOT NULL,
  toy_id uuid NOT NULL,
  toy_uuid_code text UNIQUE,
  toy_name text NOT NULL,
  toy_category text,
  toy_age_range text,
  quantity_dispatched integer DEFAULT 1,
  item_condition_out text DEFAULT 'good'::text CHECK (item_condition_out = ANY (ARRAY['excellent'::text, 'good'::text, 'fair'::text, 'damaged'::text])),
  item_condition_in text CHECK (item_condition_in = ANY (ARRAY['excellent'::text, 'good'::text, 'fair'::text, 'damaged'::text, 'missing'::text])),
  item_status text DEFAULT 'dispatched'::text CHECK (item_status = ANY (ARRAY['dispatched'::text, 'with_customer'::text, 'returned'::text, 'damaged'::text, 'lost'::text])),
  dispatch_date timestamp with time zone DEFAULT now(),
  return_date timestamp with time zone,
  damage_notes text,
  replacement_required boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dispatch_items_pkey PRIMARY KEY (id),
  CONSTRAINT dispatch_items_dispatch_order_id_fkey FOREIGN KEY (dispatch_order_id) REFERENCES public.dispatch_orders(id)
);
CREATE TABLE public.dispatch_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_address text NOT NULL,
  subscription_plan text NOT NULL,
  dispatch_status text NOT NULL DEFAULT 'pending'::text CHECK (dispatch_status = ANY (ARRAY['pending'::text, 'packed'::text, 'dispatched'::text, 'in_transit'::text, 'delivered'::text, 'return_requested'::text, 'returned'::text, 'completed'::text])),
  dispatch_date timestamp with time zone,
  expected_return_date timestamp with time zone,
  actual_return_date timestamp with time zone,
  tracking_number text,
  dispatch_notes text,
  return_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dispatch_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dispatch_pickup_pairs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  customer_subscription_status_id uuid NOT NULL,
  customer_pincode character varying NOT NULL,
  scheduled_date date NOT NULL,
  route_day character varying NOT NULL,
  operation_type character varying DEFAULT 'pickup_and_delivery'::character varying CHECK (operation_type::text = ANY (ARRAY['delivery_only'::character varying, 'pickup_only'::character varying, 'pickup_and_delivery'::character varying]::text[])),
  pickup_order_id uuid,
  pickup_dispatch_order_id uuid,
  toys_to_pickup jsonb DEFAULT '[]'::jsonb,
  toys_to_pickup_count integer DEFAULT 0,
  pickup_status character varying DEFAULT 'not_scheduled'::character varying CHECK (pickup_status::text = ANY (ARRAY['not_scheduled'::character varying, 'scheduled'::character varying, 'confirmed'::character varying, 'in_transit'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  dispatch_order_id uuid,
  new_dispatch_order_id uuid,
  toys_to_dispatch jsonb DEFAULT '[]'::jsonb,
  toys_to_dispatch_count integer DEFAULT 0,
  dispatch_status character varying DEFAULT 'pending'::character varying CHECK (dispatch_status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'packed'::character varying, 'dispatched'::character varying, 'in_transit'::character varying, 'delivered'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  pickup_route_id uuid,
  route_sequence integer DEFAULT 0,
  estimated_time_slot character varying,
  estimated_duration_minutes integer DEFAULT 15,
  actual_pickup_time timestamp with time zone,
  actual_dispatch_time timestamp with time zone,
  driver_notes text,
  customer_present boolean,
  customer_satisfaction integer CHECK (customer_satisfaction >= 1 AND customer_satisfaction <= 5),
  combined_status character varying DEFAULT 'scheduled'::character varying CHECK (combined_status::text = ANY (ARRAY['scheduled'::character varying, 'confirmed'::character varying, 'in_progress'::character varying, 'pickup_completed'::character varying, 'dispatch_completed'::character varying, 'both_completed'::character varying, 'partially_completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  notification_sent_date date,
  reminder_sent_date date,
  completion_notification_sent boolean DEFAULT false,
  pickup_quality_check jsonb DEFAULT '{}'::jsonb,
  dispatch_quality_check jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT dispatch_pickup_pairs_pkey PRIMARY KEY (id),
  CONSTRAINT dispatch_pickup_pairs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT dispatch_pickup_pairs_customer_subscription_status_id_fkey FOREIGN KEY (customer_subscription_status_id) REFERENCES public.customer_subscription_status(id),
  CONSTRAINT dispatch_pickup_pairs_pickup_order_id_fkey FOREIGN KEY (pickup_order_id) REFERENCES public.rental_orders(id),
  CONSTRAINT dispatch_pickup_pairs_pickup_dispatch_order_id_fkey FOREIGN KEY (pickup_dispatch_order_id) REFERENCES public.dispatch_orders(id),
  CONSTRAINT dispatch_pickup_pairs_dispatch_order_id_fkey FOREIGN KEY (dispatch_order_id) REFERENCES public.rental_orders(id),
  CONSTRAINT dispatch_pickup_pairs_new_dispatch_order_id_fkey FOREIGN KEY (new_dispatch_order_id) REFERENCES public.dispatch_orders(id),
  CONSTRAINT dispatch_pickup_pairs_pickup_route_id_fkey FOREIGN KEY (pickup_route_id) REFERENCES public.pickup_routes(id),
  CONSTRAINT dispatch_pickup_pairs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.drop_reasons (
  id integer NOT NULL DEFAULT nextval('drop_reasons_id_seq'::regclass),
  reason_code text NOT NULL UNIQUE,
  reason_name text NOT NULL,
  category text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT drop_reasons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.drop_steps (
  id integer NOT NULL DEFAULT nextval('drop_steps_id_seq'::regclass),
  step_name text NOT NULL UNIQUE,
  step_order integer NOT NULL,
  description text,
  is_critical boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT drop_steps_pkey PRIMARY KEY (id)
);
CREATE TABLE public.entitlements_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_tracking_id uuid,
  toys_in_possession boolean DEFAULT false,
  current_cycle_toys jsonb DEFAULT '[]'::jsonb,
  selection_window_active boolean DEFAULT false,
  next_billing_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_to_main boolean DEFAULT false,
  CONSTRAINT entitlements_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT entitlements_tracking_subscription_tracking_id_fkey FOREIGN KEY (subscription_tracking_id) REFERENCES public.subscription_tracking(id)
);
CREATE TABLE public.exchange_capacity (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pincode character varying NOT NULL,
  assigned_day character varying NOT NULL,
  service_date date NOT NULL,
  max_exchanges_per_day integer DEFAULT 25,
  current_exchanges_count integer DEFAULT 0,
  available_capacity integer DEFAULT (max_exchanges_per_day - current_exchanges_count),
  available_time_slots jsonb DEFAULT '["09:00-11:00", "11:00-13:00", "13:00-15:00", "15:00-17:00", "17:00-19:00"]'::jsonb,
  booked_time_slots jsonb DEFAULT '[]'::jsonb,
  zone character varying,
  area_name character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT exchange_capacity_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  toy_id uuid,
  alert_type text NOT NULL CHECK (alert_type = ANY (ARRAY['low_stock'::text, 'out_of_stock'::text, 'damage_reported'::text, 'overdue_return'::text, 'system_maintenance'::text, 'restock_recommendation'::text, 'system_setup'::text])),
  alert_severity text NOT NULL DEFAULT 'medium'::text CHECK (alert_severity = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])),
  message text NOT NULL,
  threshold_value integer DEFAULT 0,
  current_value integer DEFAULT 0,
  reference_type text,
  reference_id uuid,
  resolved_at timestamp with time zone,
  archived_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_alerts_toy_id_fkey FOREIGN KEY (toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.inventory_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  toy_id uuid NOT NULL,
  movement_type text NOT NULL CHECK (movement_type = ANY (ARRAY['RENTAL_OUT'::text, 'RENTAL_RETURN'::text, 'PURCHASE'::text, 'SALE'::text, 'DAMAGE'::text, 'LOSS'::text, 'MANUAL_INCREASE'::text, 'MANUAL_DECREASE'::text, 'ADJUSTMENT'::text, 'TRANSFER'::text, 'REPAIR'::text])),
  quantity_change integer NOT NULL CHECK (quantity_change <> 0),
  reference_type text,
  reference_id uuid,
  notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  archived_at timestamp with time zone,
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_movements_toy_id_fkey FOREIGN KEY (toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.jwt_secrets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key_id text NOT NULL UNIQUE,
  secret_key text NOT NULL,
  algorithm text DEFAULT 'HS256'::text,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  CONSTRAINT jwt_secrets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.migration_customer_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  migration_customer_id character varying,
  current_user_uuid uuid,
  address_type character varying,
  full_address text,
  city character varying,
  state character varying,
  pincode character varying,
  landmark character varying,
  is_primary boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT migration_customer_addresses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.migration_customer_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  migration_customer_id character varying NOT NULL UNIQUE,
  username character varying,
  phone character varying,
  phone_normalized character varying,
  email character varying,
  first_name character varying,
  last_name character varying,
  phone_verified boolean DEFAULT false,
  role character varying DEFAULT 'customer'::character varying,
  customer_tier character varying,
  total_lifetime_value numeric,
  total_orders integer DEFAULT 0,
  average_order_value numeric DEFAULT 0,
  primary_child_age_group character varying,
  is_active boolean DEFAULT true,
  last_login timestamp without time zone,
  preferences jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT migration_customer_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.migration_log (
  id integer NOT NULL DEFAULT nextval('migration_log_id_seq'::regclass),
  migration_name text NOT NULL UNIQUE,
  description text,
  applied_at timestamp with time zone DEFAULT now(),
  CONSTRAINT migration_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.migration_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  migration_order_id character varying,
  order_csv_id character varying,
  product_name character varying,
  product_sku character varying,
  quantity integer,
  unit_price numeric,
  total_price numeric,
  age_group character varying,
  category character varying,
  rental_duration_days integer,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT migration_order_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.migration_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  migration_order_id character varying NOT NULL UNIQUE,
  migration_customer_id character varying,
  current_user_uuid uuid,
  order_date date,
  status character varying,
  total_amount numeric,
  currency character varying DEFAULT 'INR'::character varying,
  payment_method character varying,
  payment_status character varying,
  rental_start_date date,
  rental_end_date date,
  delivered_at timestamp without time zone,
  returned_at timestamp without time zone,
  customer_age_group character varying,
  shipping_address jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT migration_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.migration_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  migration_product_id character varying NOT NULL UNIQUE,
  name character varying,
  description text,
  category character varying,
  age_group character varying,
  brand character varying,
  sku character varying,
  rental_price numeric,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT migration_products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.next_cycle_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  current_order_id uuid NOT NULL,
  queued_toys jsonb NOT NULL,
  shipping_address jsonb,
  special_instructions text,
  status character varying DEFAULT 'pending'::character varying,
  queue_created_at timestamp without time zone DEFAULT now(),
  processed_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT next_cycle_queue_pkey PRIMARY KEY (id),
  CONSTRAINT next_cycle_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT next_cycle_queue_current_order_id_fkey FOREIGN KEY (current_order_id) REFERENCES public.rental_orders(id)
);
CREATE TABLE public.notification_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  order_id uuid NOT NULL,
  notification_type character varying NOT NULL CHECK (notification_type::text = ANY (ARRAY['order_confirmed'::character varying, 'order_shipped'::character varying, 'order_delivered'::character varying, 'pickup_scheduled'::character varying, 'pickup_reminder'::character varying, 'selection_window_opened'::character varying, 'custom'::character varying]::text[])),
  phone_number character varying NOT NULL,
  message_content text NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying, 'delivered'::character varying, 'read'::character varying]::text[])),
  external_message_id character varying,
  error_message text,
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  sent_at timestamp with time zone NOT NULL DEFAULT now(),
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  template_used character varying,
  channel character varying DEFAULT 'whatsapp'::character varying CHECK (channel::text = ANY (ARRAY['whatsapp'::character varying, 'sms'::character varying, 'email'::character varying]::text[])),
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_logs_pkey PRIMARY KEY (id),
  CONSTRAINT notification_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.offer_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  color_code text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offer_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.offer_category_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  offer_id uuid NOT NULL,
  category_id uuid NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offer_category_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT offer_category_assignments_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.promotional_offers(id),
  CONSTRAINT offer_category_assignments_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.offer_categories(id)
);
CREATE TABLE public.offer_redemption_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  offer_id uuid NOT NULL,
  rule_type text NOT NULL CHECK (rule_type = ANY (ARRAY['age_range'::text, 'location'::text, 'subscription_duration'::text, 'order_count'::text, 'total_spent'::text])),
  rule_value jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offer_redemption_rules_pkey PRIMARY KEY (id),
  CONSTRAINT offer_redemption_rules_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.promotional_offers(id)
);
CREATE TABLE public.offer_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  template_data jsonb NOT NULL,
  category text,
  is_active boolean DEFAULT true,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT offer_templates_pkey PRIMARY KEY (id),
  CONSTRAINT offer_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.offer_usage_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  offer_id uuid NOT NULL,
  user_id uuid NOT NULL,
  order_id uuid,
  discount_amount numeric NOT NULL CHECK (discount_amount >= 0::numeric),
  original_amount numeric NOT NULL CHECK (original_amount > 0::numeric),
  final_amount numeric NOT NULL CHECK (final_amount >= 0::numeric),
  used_at timestamp with time zone DEFAULT now(),
  user_agent text,
  ip_address inet,
  CONSTRAINT offer_usage_history_pkey PRIMARY KEY (id),
  CONSTRAINT offer_usage_history_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.promotional_offers(id),
  CONSTRAINT offer_usage_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  toy_id uuid NOT NULL,
  quantity integer DEFAULT 1,
  rental_price numeric,
  created_at timestamp with time zone DEFAULT now(),
  unit_price numeric,
  total_price numeric,
  subscription_category text,
  age_group text,
  ride_on_toy_id uuid,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_ride_on_toy_id_fkey FOREIGN KEY (ride_on_toy_id) REFERENCES public.toys(id),
  CONSTRAINT order_items_toy_id_fkey FOREIGN KEY (toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::order_status,
  total_amount numeric,
  shipping_address jsonb,
  rental_start_date timestamp with time zone,
  rental_end_date timestamp with time zone,
  returned_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  order_type text DEFAULT 'subscription'::text,
  base_amount numeric NOT NULL DEFAULT 0,
  gst_amount numeric NOT NULL DEFAULT 0,
  discount_amount numeric NOT NULL DEFAULT 0,
  dispatch_status character varying DEFAULT 'New Delivery'::character varying CHECK (dispatch_status::text = ANY (ARRAY['New Delivery'::character varying::text, 'Pickup & Delivery'::character varying::text, 'Pickup'::character varying::text])),
  estimated_delivery_date date,
  estimated_pickup_date date,
  actual_delivery_date date,
  pickup_status_operational character varying DEFAULT 'pending'::character varying CHECK (pickup_status_operational::text = ANY (ARRAY['pending'::character varying, 'complete'::character varying]::text[])),
  plus_code character varying,
  delivery_day character varying,
  assigned_pickup_day character varying,
  pincode_assigned character varying,
  dispatch_notes text,
  pickup_notes text,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.otp_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone_number text NOT NULL,
  otp_code text NOT NULL,
  is_verified boolean DEFAULT false,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  provider character varying DEFAULT '2factor'::character varying,
  provider_message_id character varying,
  session_id text,
  verified_at timestamp with time zone,
  CONSTRAINT otp_verifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pause_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid NOT NULL,
  pause_start_date timestamp with time zone NOT NULL DEFAULT now(),
  pause_end_date timestamp with time zone,
  months_paused integer NOT NULL,
  reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pause_records_pkey PRIMARY KEY (id),
  CONSTRAINT pause_records_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.payment_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  razorpay_order_id text UNIQUE,
  razorpay_payment_id text,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  status text DEFAULT 'created'::text,
  order_type text NOT NULL,
  order_items jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_orders_pkey PRIMARY KEY (id),
  CONSTRAINT payment_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.payment_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  razorpay_order_id text NOT NULL,
  user_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'INR'::text,
  status text DEFAULT 'created'::text,
  order_type text NOT NULL,
  order_items jsonb,
  user_email text,
  user_phone text,
  razorpay_payment_id text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  total_amount numeric,
  base_amount numeric,
  gst_amount numeric,
  CONSTRAINT payment_tracking_pkey PRIMARY KEY (id)
);
CREATE TABLE public.perk_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid NOT NULL,
  perk_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  assigned_date timestamp with time zone NOT NULL DEFAULT now(),
  delivered_date timestamp with time zone,
  toy_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT perk_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT perk_assignments_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.phone_format_backup (
  backup_timestamp text,
  user_id uuid,
  original_custom_users_phone text,
  original_rental_orders_phone text,
  first_name text,
  last_name text,
  rental_order_count bigint
);
CREATE TABLE public.pickup_routes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  route_name character varying NOT NULL,
  pickup_date date NOT NULL,
  pickup_day character varying NOT NULL,
  assigned_driver_id uuid,
  assigned_driver_name character varying,
  vehicle_number character varying,
  total_planned_pickups integer DEFAULT 0,
  total_completed_pickups integer DEFAULT 0,
  total_failed_pickups integer DEFAULT 0,
  route_start_time time without time zone,
  route_end_time time without time zone,
  estimated_duration_minutes integer,
  actual_duration_minutes integer,
  covered_pincodes ARRAY,
  covered_zones character varying,
  optimized_order jsonb,
  total_distance_km numeric,
  total_fuel_cost numeric,
  route_status character varying DEFAULT 'planned'::character varying CHECK (route_status::text = ANY (ARRAY['planned'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'failed'::character varying]::text[])),
  success_rate numeric,
  customer_satisfaction_score numeric,
  notes text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT pickup_routes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pickup_system_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  config_key character varying NOT NULL UNIQUE,
  config_value text,
  config_type character varying DEFAULT 'string'::character varying CHECK (config_type::text = ANY (ARRAY['string'::character varying, 'integer'::character varying, 'boolean'::character varying, 'json'::character varying]::text[])),
  description text,
  is_active boolean DEFAULT true,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT pickup_system_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pincode_pickup_schedule (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pincode character varying NOT NULL UNIQUE,
  area_name character varying,
  zone character varying,
  pickup_day character varying NOT NULL CHECK (pickup_day::text = ANY (ARRAY['monday'::character varying, 'tuesday'::character varying, 'wednesday'::character varying, 'thursday'::character varying, 'friday'::character varying, 'saturday'::character varying, 'sunday'::character varying]::text[])),
  delivery_day character varying NOT NULL CHECK (delivery_day::text = ANY (ARRAY['monday'::character varying, 'tuesday'::character varying, 'wednesday'::character varying, 'thursday'::character varying, 'friday'::character varying, 'saturday'::character varying, 'sunday'::character varying]::text[])),
  max_pickups_per_day integer DEFAULT 25,
  min_pickups_per_day integer DEFAULT 10,
  current_capacity_used integer DEFAULT 0,
  is_active boolean DEFAULT true,
  priority_level integer DEFAULT 1,
  estimated_travel_time_minutes integer DEFAULT 30,
  pickup_window_start time without time zone DEFAULT '09:00:00'::time without time zone,
  pickup_window_end time without time zone DEFAULT '18:00:00'::time without time zone,
  notes text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT pincode_pickup_schedule_pkey PRIMARY KEY (id)
);
CREATE TABLE public.promotional_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  campaign_type text NOT NULL CHECK (campaign_type = ANY (ARRAY['seasonal'::text, 'referral'::text, 'loyalty'::text, 'welcome'::text, 'retention'::text])),
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  budget_limit numeric CHECK (budget_limit IS NULL OR budget_limit > 0::numeric),
  spent_amount numeric DEFAULT 0 CHECK (spent_amount >= 0::numeric),
  target_audience jsonb,
  is_active boolean DEFAULT true,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promotional_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT promotional_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.promotional_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  type text NOT NULL CHECK (type = ANY (ARRAY['discount_percentage'::text, 'discount_amount'::text, 'free_month'::text, 'free_toys'::text, 'upgrade'::text])),
  value numeric NOT NULL CHECK (value > 0::numeric),
  min_order_value numeric DEFAULT 0 CHECK (min_order_value >= 0::numeric),
  max_discount_amount numeric,
  target_plans ARRAY DEFAULT '{}'::text[],
  usage_limit integer CHECK (usage_limit IS NULL OR usage_limit > 0),
  usage_count integer DEFAULT 0 CHECK (usage_count >= 0),
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  auto_apply boolean DEFAULT false,
  stackable boolean DEFAULT false,
  first_time_users_only boolean DEFAULT false,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  display_on_homepage boolean DEFAULT false,
  display_on_pricing boolean DEFAULT true,
  display_in_header boolean DEFAULT false,
  display_priority integer DEFAULT 1,
  CONSTRAINT promotional_offers_pkey PRIMARY KEY (id),
  CONSTRAINT promotional_offers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.purchase_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL,
  toy_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_cost numeric NOT NULL CHECK (unit_cost >= 0::numeric),
  total_cost numeric DEFAULT ((quantity)::numeric * unit_cost),
  received_quantity integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_items_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_items_toy_id_fkey FOREIGN KEY (toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number text NOT NULL UNIQUE,
  supplier_id uuid NOT NULL,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending'::text, 'approved'::text, 'ordered'::text, 'shipped'::text, 'received'::text, 'cancelled'::text])),
  total_amount numeric DEFAULT 0,
  expected_delivery_date date,
  actual_delivery_date date,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.queue_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  original_subscription_id uuid,
  order_number character varying UNIQUE,
  selected_toys jsonb NOT NULL DEFAULT '[]'::jsonb,
  queue_cycle_number integer DEFAULT 1,
  queue_order_type character varying DEFAULT 'next_cycle'::character varying CHECK (queue_order_type::text = ANY (ARRAY['next_cycle'::character varying, 'modification'::character varying, 'emergency_change'::character varying]::text[])),
  total_amount numeric NOT NULL DEFAULT 0.00,
  base_amount numeric NOT NULL DEFAULT 0.00,
  gst_amount numeric NOT NULL DEFAULT 0.00,
  coupon_discount numeric NOT NULL DEFAULT 0.00,
  applied_coupon character varying,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying, 'cancelled'::character varying]::text[])),
  payment_id character varying,
  razorpay_order_id character varying,
  status character varying DEFAULT 'processing'::character varying CHECK (status::text = ANY (ARRAY['processing'::character varying, 'confirmed'::character varying, 'preparing'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])),
  delivery_address jsonb NOT NULL DEFAULT '{}'::jsonb,
  delivery_instructions text,
  estimated_delivery_date date,
  actual_delivery_date date,
  current_plan_id character varying,
  age_group character varying,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  processed_at timestamp with time zone,
  created_by uuid,
  notes text,
  subscription_cycle_id uuid,
  subscription_cycle_number integer,
  cycle_based_delivery_date date,
  subscription_aligned boolean DEFAULT false,
  dispatch_status character varying DEFAULT 'Pickup & Delivery'::character varying CHECK (dispatch_status::text = ANY (ARRAY['New Delivery'::character varying::text, 'Pickup & Delivery'::character varying::text, 'Pickup'::character varying::text])),
  estimated_pickup_date date,
  pickup_status_operational character varying DEFAULT 'pending'::character varying CHECK (pickup_status_operational::text = ANY (ARRAY['pending'::character varying, 'complete'::character varying]::text[])),
  plus_code character varying,
  delivery_day character varying,
  assigned_pickup_day character varying,
  pincode_assigned character varying,
  dispatch_notes text,
  pickup_notes text,
  CONSTRAINT queue_orders_pkey PRIMARY KEY (id),
  CONSTRAINT queue_orders_subscription_cycle_id_fkey FOREIGN KEY (subscription_cycle_id) REFERENCES public.subscription_cycles(id),
  CONSTRAINT queue_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT queue_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.custom_users(id),
  CONSTRAINT queue_orders_original_subscription_id_fkey FOREIGN KEY (original_subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.queue_orders_address_backup (
  id uuid,
  order_number character varying,
  user_id uuid,
  queue_order_type character varying,
  delivery_address jsonb,
  created_at timestamp with time zone,
  backup_created_at timestamp with time zone
);
CREATE TABLE public.rental_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number character varying NOT NULL DEFAULT generate_order_number() UNIQUE,
  user_id uuid NOT NULL,
  legacy_order_id uuid,
  legacy_created_at timestamp without time zone,
  migrated_at timestamp without time zone DEFAULT now(),
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  order_type character varying NOT NULL DEFAULT 'subscription'::character varying CHECK (order_type::text = ANY (ARRAY['subscription'::character varying, 'one_time'::character varying, 'trial'::character varying, 'ride_on'::character varying]::text[])),
  subscription_plan character varying,
  total_amount numeric NOT NULL DEFAULT 0.00,
  base_amount numeric DEFAULT 0.00,
  gst_amount numeric DEFAULT 0.00,
  discount_amount numeric DEFAULT 0.00,
  payment_status character varying DEFAULT 'pending'::character varying,
  payment_method character varying,
  razorpay_order_id character varying,
  razorpay_payment_id character varying,
  cycle_number integer NOT NULL DEFAULT 1 CHECK (cycle_number > 0),
  rental_start_date date NOT NULL,
  rental_end_date date NOT NULL,
  delivery_date date,
  returned_date date,
  return_status character varying DEFAULT 'pending'::character varying,
  toys_data jsonb NOT NULL DEFAULT '[]'::jsonb,
  toys_delivered_count integer DEFAULT 0,
  toys_returned_count integer DEFAULT 0,
  shipping_address jsonb NOT NULL DEFAULT '{}'::jsonb,
  delivery_instructions text,
  pickup_instructions text,
  next_cycle_address jsonb DEFAULT '{}'::jsonb,
  next_cycle_toys_selected jsonb DEFAULT '[]'::jsonb,
  next_cycle_prepared boolean DEFAULT false,
  subscription_id uuid,
  age_group character varying,
  subscription_category character varying,
  quality_rating integer CHECK (quality_rating >= 1 AND quality_rating <= 5),
  feedback text,
  damage_reported boolean DEFAULT false,
  damage_details jsonb DEFAULT '{}'::jsonb,
  admin_notes text,
  internal_status character varying,
  dispatch_tracking_number character varying,
  return_tracking_number character varying,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  user_phone text,
  confirmed_at timestamp without time zone,
  shipped_at timestamp without time zone,
  delivered_at timestamp without time zone,
  cancelled_at timestamp without time zone,
  coupon_code character varying,
  razorpay_signature character varying,
  payment_amount numeric,
  payment_currency character varying DEFAULT 'INR'::character varying,
  subscription_status text DEFAULT 'active'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'paused'::text, 'expired'::text, 'cancelled'::text])),
  selection_window_status text DEFAULT 'auto'::text CHECK (selection_window_status = ANY (ARRAY['auto'::text, 'manual_open'::text, 'manual_closed'::text, 'force_open'::text, 'force_closed'::text, 'auto_closed'::text, 'auto_open'::text])),
  selection_window_opened_at timestamp with time zone,
  selection_window_closed_at timestamp with time zone,
  manual_selection_control boolean DEFAULT false,
  selection_window_auto_close_date date,
  selection_window_notes text,
  pickup_scheduled_date date,
  pickup_status character varying DEFAULT 'not_scheduled'::character varying CHECK (pickup_status::text = ANY (ARRAY['not_scheduled'::character varying, 'scheduled'::character varying, 'confirmed'::character varying, 'in_transit'::character varying, 'completed'::character varying, 'failed'::character varying, 'rescheduled'::character varying]::text[])),
  pickup_notification_sent boolean DEFAULT false,
  pickup_notification_date date,
  scheduled_pickup_id uuid,
  customer_pickup_day character varying,
  pickup_cycle_day integer,
  is_archived boolean DEFAULT false,
  archived_at timestamp with time zone,
  archived_reason text,
  dispatch_status character varying CHECK (dispatch_status::text = ANY (ARRAY['New Delivery'::character varying::text, 'Pickup & Delivery'::character varying::text, 'Pickup'::character varying::text])),
  estimated_delivery_date date,
  estimated_pickup_date date,
  actual_delivery_date date,
  pickup_status_operational character varying DEFAULT 'pending'::character varying CHECK (pickup_status_operational::text = ANY (ARRAY['pending'::character varying, 'complete'::character varying]::text[])),
  plus_code character varying,
  delivery_day character varying,
  assigned_pickup_day character varying,
  pincode_assigned character varying,
  dispatch_notes text,
  pickup_notes text,
  customer_type character varying DEFAULT 'existing'::character varying CHECK (customer_type::text = ANY (ARRAY['new'::character varying, 'existing'::character varying]::text[])),
  paired_pickup_order_id uuid,
  paired_dispatch_order_id uuid,
  requires_pickup boolean DEFAULT false,
  requires_dispatch boolean DEFAULT true,
  dispatch_pickup_pair_id uuid,
  subscription_cycle_context jsonb DEFAULT '{}'::jsonb,
  toys_possession_status jsonb DEFAULT '{}'::jsonb,
  exchange_scheduled_date date,
  exchange_type character varying,
  exchange_status character varying DEFAULT 'not_scheduled'::character varying,
  exchange_id uuid,
  is_pause_order boolean DEFAULT false,
  is_resume_order boolean DEFAULT false,
  CONSTRAINT rental_orders_pkey PRIMARY KEY (id),
  CONSTRAINT rental_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.custom_users(id),
  CONSTRAINT rental_orders_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT rental_orders_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.custom_users(id),
  CONSTRAINT rental_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT rental_orders_scheduled_pickup_id_fkey FOREIGN KEY (scheduled_pickup_id) REFERENCES public.scheduled_pickups(id),
  CONSTRAINT rental_orders_paired_pickup_order_id_fkey FOREIGN KEY (paired_pickup_order_id) REFERENCES public.rental_orders(id),
  CONSTRAINT rental_orders_paired_dispatch_order_id_fkey FOREIGN KEY (paired_dispatch_order_id) REFERENCES public.rental_orders(id),
  CONSTRAINT rental_orders_dispatch_pickup_pair_id_fkey FOREIGN KEY (dispatch_pickup_pair_id) REFERENCES public.dispatch_pickup_pairs(id),
  CONSTRAINT rental_orders_exchange_id_fkey FOREIGN KEY (exchange_id) REFERENCES public.toy_exchanges(id)
);
CREATE TABLE public.rental_orders_address_backup (
  id uuid,
  order_number character varying,
  user_id uuid,
  shipping_address jsonb,
  created_at timestamp without time zone,
  backup_created_at timestamp with time zone
);
CREATE TABLE public.rental_orders_phone_backup (
  id uuid,
  user_phone text,
  created_at timestamp without time zone
);
CREATE TABLE public.rental_orders_phone_backup_2025_07_05_02_08_38 (
  id uuid,
  user_phone text,
  new_phone text
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  toy_id uuid NOT NULL,
  order_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT reviews_toy_id_fkey FOREIGN KEY (toy_id) REFERENCES public.toys(id),
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.scheduled_pickups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rental_order_id uuid,
  user_id uuid,
  pickup_route_id uuid,
  scheduled_pickup_date date NOT NULL,
  scheduled_pickup_time_start time without time zone,
  scheduled_pickup_time_end time without time zone,
  pickup_day character varying NOT NULL,
  customer_name character varying,
  customer_phone character varying,
  customer_address jsonb,
  pincode character varying NOT NULL,
  subscription_id uuid,
  cycle_number integer,
  cycle_end_date date,
  days_into_cycle integer,
  toys_to_pickup jsonb,
  toys_count integer DEFAULT 0,
  estimated_pickup_value numeric,
  actual_pickup_date date,
  actual_pickup_time time without time zone,
  pickup_status character varying DEFAULT 'scheduled'::character varying CHECK (pickup_status::text = ANY (ARRAY['scheduled'::character varying, 'confirmed'::character varying, 'in_transit'::character varying, 'completed'::character varying, 'failed'::character varying, 'rescheduled'::character varying, 'cancelled'::character varying]::text[])),
  toys_actually_collected jsonb,
  toys_collected_count integer DEFAULT 0,
  toys_missing_count integer DEFAULT 0,
  toys_damaged_count integer DEFAULT 0,
  customer_was_present boolean,
  pickup_notes text,
  customer_feedback text,
  customer_satisfaction integer,
  notification_sent_date date,
  days_advance_notice integer DEFAULT 5,
  reminder_sent boolean DEFAULT false,
  reschedule_count integer DEFAULT 0,
  reschedule_reason text,
  original_scheduled_date date,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT scheduled_pickups_pkey PRIMARY KEY (id),
  CONSTRAINT scheduled_pickups_rental_order_id_fkey FOREIGN KEY (rental_order_id) REFERENCES public.rental_orders(id),
  CONSTRAINT scheduled_pickups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT scheduled_pickups_pickup_route_id_fkey FOREIGN KEY (pickup_route_id) REFERENCES public.pickup_routes(id)
);
CREATE TABLE public.stock_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  toy_id uuid NOT NULL,
  alert_type text NOT NULL CHECK (alert_type = ANY (ARRAY['low_stock'::text, 'out_of_stock'::text, 'reorder_needed'::text, 'overstock'::text])),
  threshold_quantity integer NOT NULL,
  current_quantity integer NOT NULL,
  is_resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT stock_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT stock_alerts_toy_id_fkey FOREIGN KEY (toy_id) REFERENCES public.toys(id),
  CONSTRAINT stock_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text NOT NULL UNIQUE,
  razorpay_customer_id text,
  razorpay_subscription_id text,
  subscribed boolean NOT NULL DEFAULT false,
  subscription_tier text,
  subscription_end timestamp with time zone,
  payment_status text DEFAULT 'pending'::text,
  last_payment_date timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscribers_pkey PRIMARY KEY (id),
  CONSTRAINT subscribers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.subscription_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['plan_change'::text, 'pause'::text, 'resume'::text, 'cancel'::text, 'extend'::text, 'add_free_month'::text, 'billing_update'::text, 'credit'::text, 'refund'::text])),
  action_data jsonb NOT NULL,
  performed_by text NOT NULL,
  performed_at timestamp with time zone DEFAULT now(),
  notes text,
  amount_change numeric,
  effective_date timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_actions_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_actions_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.user_subscriptions(id)
);
CREATE TABLE public.subscription_cycles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL,
  user_id uuid NOT NULL,
  cycle_number integer NOT NULL,
  cycle_start_date date NOT NULL,
  cycle_end_date date NOT NULL,
  selection_window_start date NOT NULL,
  selection_window_end date NOT NULL,
  selection_opened_at timestamp with time zone,
  selection_closed_at timestamp with time zone,
  toys_selected_at timestamp with time zone,
  selected_toys jsonb DEFAULT '[]'::jsonb,
  toys_count integer DEFAULT 0,
  total_toy_value numeric DEFAULT 0.00,
  delivery_scheduled_date date,
  delivery_actual_date date,
  delivery_status text DEFAULT 'pending'::text CHECK (delivery_status = ANY (ARRAY['pending'::text, 'scheduled'::text, 'shipped'::text, 'delivered'::text, 'failed'::text, 'cancelled'::text])),
  tracking_number text,
  delivery_address jsonb,
  cycle_status text DEFAULT 'upcoming'::text CHECK (cycle_status = ANY (ARRAY['upcoming'::text, 'active'::text, 'selection_open'::text, 'selection_closed'::text, 'preparing'::text, 'shipped'::text, 'delivered'::text, 'completed'::text, 'cancelled'::text])),
  completed_at timestamp with time zone,
  billing_cycle_id text,
  billing_amount numeric,
  billing_status text DEFAULT 'pending'::text CHECK (billing_status = ANY (ARRAY['pending'::text, 'billed'::text, 'paid'::text, 'failed'::text, 'refunded'::text])),
  plan_id_at_cycle text NOT NULL,
  plan_details jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT subscription_cycles_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_cycles_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT subscription_cycles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.subscription_extensions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL,
  extension_type text NOT NULL CHECK (extension_type = ANY (ARRAY['days'::text, 'free_month'::text, 'pause_compensation'::text])),
  days_added integer NOT NULL,
  reason text NOT NULL,
  performed_by text NOT NULL,
  performed_at timestamp with time zone DEFAULT now(),
  original_end_date timestamp with time zone NOT NULL,
  new_end_date timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_extensions_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_extensions_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.user_subscriptions(id)
);
CREATE TABLE public.subscription_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL,
  previous_plan_type text NOT NULL,
  new_plan_type text NOT NULL,
  previous_amount numeric NOT NULL,
  new_amount numeric NOT NULL,
  prorated_amount numeric NOT NULL,
  change_reason text,
  effective_date timestamp with time zone NOT NULL,
  performed_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_history_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_history_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.user_subscriptions(id)
);
CREATE TABLE public.subscription_management (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  order_id uuid NOT NULL,
  subscription_id uuid NOT NULL,
  cycle_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  cycle_number integer NOT NULL CHECK (cycle_number > 0),
  cycle_status character varying DEFAULT 'pending'::character varying CHECK (cycle_status::text = ANY (ARRAY['pending'::character varying, 'active'::character varying, 'completed'::character varying, 'skipped'::character varying, 'cancelled'::character varying]::text[])),
  cycle_start_date date NOT NULL,
  cycle_end_date date NOT NULL,
  selection_window_start date NOT NULL,
  selection_window_end date NOT NULL,
  selection_window_status character varying DEFAULT 'upcoming'::character varying CHECK (selection_window_status::text = ANY (ARRAY['upcoming'::character varying, 'open'::character varying, 'closed'::character varying, 'manual'::character varying]::text[])),
  selected_toys jsonb DEFAULT '[]'::jsonb,
  toys_selected_at timestamp with time zone,
  toys_count integer DEFAULT 0,
  total_toy_value numeric DEFAULT 0.00,
  delivery_status character varying DEFAULT 'pending'::character varying CHECK (delivery_status::text = ANY (ARRAY['pending'::character varying, 'scheduled'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  delivery_scheduled_date date,
  delivery_actual_date date,
  tracking_number character varying,
  delivery_address jsonb,
  plan_id character varying NOT NULL,
  plan_name character varying NOT NULL,
  plan_details jsonb DEFAULT '{}'::jsonb,
  manual_override boolean DEFAULT false,
  admin_notes text,
  created_by uuid,
  last_modified_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT subscription_management_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_management_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT subscription_management_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.rental_orders(id),
  CONSTRAINT subscription_management_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.custom_users(id),
  CONSTRAINT subscription_management_last_modified_by_fkey FOREIGN KEY (last_modified_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.subscription_pause_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  rental_order_id uuid NOT NULL,
  pause_start_date timestamp with time zone NOT NULL,
  pause_end_date timestamp with time zone,
  pause_duration_days integer,
  pause_reason text,
  paused_by uuid,
  resumed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_pause_periods_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_pause_periods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT subscription_pause_periods_rental_order_id_fkey FOREIGN KEY (rental_order_id) REFERENCES public.rental_orders(id),
  CONSTRAINT subscription_pause_periods_paused_by_fkey FOREIGN KEY (paused_by) REFERENCES public.custom_users(id),
  CONSTRAINT subscription_pause_periods_resumed_by_fkey FOREIGN KEY (resumed_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.subscription_pause_resume (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid,
  user_id uuid,
  subscription_plan character varying NOT NULL,
  operation_type character varying NOT NULL CHECK (operation_type::text = ANY (ARRAY['PAUSE'::character varying, 'RESUME'::character varying]::text[])),
  operation_status character varying DEFAULT 'requested'::character varying CHECK (operation_status::text = ANY (ARRAY['requested'::character varying, 'scheduled'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  pause_requested_at timestamp with time zone,
  toys_to_collect jsonb DEFAULT '[]'::jsonb,
  pickup_scheduled_date date,
  pickup_completed_at timestamp with time zone,
  resume_requested_at timestamp with time zone,
  toys_to_deliver jsonb DEFAULT '[]'::jsonb,
  dispatch_scheduled_date date,
  dispatch_completed_at timestamp with time zone,
  customer_pincode character varying,
  customer_assigned_day character varying,
  exchange_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT subscription_pause_resume_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_pause_resume_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT subscription_pause_resume_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT subscription_pause_resume_exchange_id_fkey FOREIGN KEY (exchange_id) REFERENCES public.toy_exchanges(id)
);
CREATE TABLE public.subscription_pauses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subscription_id uuid NOT NULL,
  pause_start timestamp with time zone NOT NULL,
  pause_end timestamp with time zone,
  pause_days integer NOT NULL,
  reason text,
  performed_by text NOT NULL,
  resumed_at timestamp with time zone,
  resumed_by text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_pauses_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_pauses_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.user_subscriptions(id)
);
CREATE TABLE public.subscription_plans (
  plan_type text NOT NULL,
  price numeric NOT NULL,
  max_toys integer NOT NULL,
  max_extensions integer NOT NULL,
  features jsonb DEFAULT '{}'::jsonb,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscription_plans_pkey PRIMARY KEY (plan_type)
);
CREATE TABLE public.subscription_toy_selections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid NOT NULL,
  cycle_month date NOT NULL,
  selection_step integer NOT NULL DEFAULT 1,
  toy_type text NOT NULL,
  toy_id uuid,
  status text NOT NULL DEFAULT 'pending'::text,
  selected_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT subscription_toy_selections_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscription_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  razorpay_payment_id text NOT NULL UNIQUE,
  razorpay_order_id text NOT NULL,
  plan_id text NOT NULL,
  status text DEFAULT 'active'::text,
  subscription_type text DEFAULT 'monthly'::text,
  start_date date DEFAULT CURRENT_DATE,
  end_date date DEFAULT (CURRENT_DATE + '1 mon'::interval),
  current_period_start date DEFAULT CURRENT_DATE,
  current_period_end date DEFAULT (CURRENT_DATE + '1 mon'::interval),
  selected_toys jsonb DEFAULT '[]'::jsonb,
  age_group text,
  ride_on_toy_id uuid,
  payment_amount numeric,
  payment_currency text DEFAULT 'INR'::text,
  payment_status text DEFAULT 'completed'::text,
  order_items jsonb,
  shipping_address jsonb,
  delivery_instructions text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  synced_to_main boolean DEFAULT false,
  CONSTRAINT subscription_tracking_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_id text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  start_date timestamp with time zone NOT NULL DEFAULT now(),
  end_date timestamp with time zone NOT NULL,
  current_period_start timestamp with time zone NOT NULL DEFAULT now(),
  current_period_end timestamp with time zone NOT NULL,
  pause_balance integer NOT NULL DEFAULT 0,
  auto_renew boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  age_group text,
  current_selection_step integer DEFAULT 1,
  current_cycle_start date,
  current_cycle_end date,
  toys_delivered_date timestamp with time zone,
  toys_return_due_date timestamp with time zone,
  next_selection_window_start timestamp with time zone,
  cycle_status USER-DEFINED DEFAULT 'selection'::cycle_status_enum,
  cycle_start_date date,
  cycle_end_date date,
  cycle_number integer DEFAULT 1,
  last_selection_date timestamp with time zone,
  next_selection_window_end date,
  subscription_start_date date DEFAULT CURRENT_DATE,
  total_cycles_completed integer DEFAULT 0,
  current_cycle_status text DEFAULT 'active'::text CHECK (current_cycle_status = ANY (ARRAY['active'::text, 'selection_open'::text, 'selection_closed'::text, 'delivery_pending'::text, 'completed'::text, 'paused'::text])),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_person text,
  email text,
  phone text,
  address jsonb DEFAULT '{}'::jsonb,
  lead_time_days integer DEFAULT 14,
  minimum_order_value numeric DEFAULT 0,
  reliability_score integer DEFAULT 5 CHECK (reliability_score >= 1 AND reliability_score <= 5),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.toy_exchanges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rental_order_id uuid,
  exchange_type character varying NOT NULL CHECK (exchange_type::text = ANY (ARRAY['EXCHANGE'::character varying, 'PICKUP_ONLY'::character varying, 'DISPATCH_ONLY'::character varying, 'FIRST_DELIVERY'::character varying]::text[])),
  order_classification character varying NOT NULL CHECK (order_classification::text = ANY (ARRAY['SUB'::character varying, 'QU'::character varying, 'REGULAR'::character varying]::text[])),
  customer_id uuid,
  customer_name character varying,
  customer_phone character varying,
  customer_address jsonb,
  pincode character varying NOT NULL,
  assigned_day character varying NOT NULL CHECK (assigned_day::text = ANY (ARRAY['monday'::character varying, 'tuesday'::character varying, 'wednesday'::character varying, 'thursday'::character varying, 'friday'::character varying, 'saturday'::character varying, 'sunday'::character varying]::text[])),
  subscription_plan character varying,
  cycle_number integer,
  is_pause_order boolean DEFAULT false,
  is_resume_order boolean DEFAULT false,
  scheduled_date date NOT NULL,
  scheduled_time_slot character varying,
  toys_to_pickup jsonb DEFAULT '[]'::jsonb,
  toys_to_dispatch jsonb DEFAULT '[]'::jsonb,
  pickup_toy_count integer DEFAULT 0,
  dispatch_toy_count integer DEFAULT 0,
  exchange_status character varying DEFAULT 'scheduled'::character varying CHECK (exchange_status::text = ANY (ARRAY['scheduled'::character varying, 'confirmed'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying, 'rescheduled'::character varying]::text[])),
  pickup_completed boolean DEFAULT false,
  dispatch_completed boolean DEFAULT false,
  route_sequence integer,
  estimated_duration_minutes integer DEFAULT 30,
  actual_exchange_date date,
  actual_exchange_time time without time zone,
  toys_actually_collected jsonb DEFAULT '[]'::jsonb,
  toys_actually_delivered jsonb DEFAULT '[]'::jsonb,
  exchange_notes text,
  customer_satisfaction integer CHECK (customer_satisfaction >= 1 AND customer_satisfaction <= 5),
  toys_condition_on_pickup jsonb DEFAULT '[]'::jsonb,
  toys_condition_on_dispatch jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT toy_exchanges_pkey PRIMARY KEY (id),
  CONSTRAINT toy_exchanges_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.custom_users(id),
  CONSTRAINT toy_exchanges_rental_order_id_fkey FOREIGN KEY (rental_order_id) REFERENCES public.rental_orders(id)
);
CREATE TABLE public.toy_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  toy_id uuid NOT NULL,
  image_url text NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT toy_images_pkey PRIMARY KEY (id),
  CONSTRAINT toy_images_toy_id_fkey FOREIGN KEY (toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.toy_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  toy_id uuid NOT NULL UNIQUE,
  total_quantity integer NOT NULL DEFAULT 0,
  available_quantity integer NOT NULL DEFAULT 0,
  rented_quantity integer NOT NULL DEFAULT 0,
  reorder_level integer DEFAULT 5,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  updated_by text DEFAULT 'system'::text,
  CONSTRAINT toy_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT toy_inventory_toy_id_fkey FOREIGN KEY (toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.toys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category USER-DEFINED NOT NULL,
  age_range text NOT NULL,
  brand text,
  retail_price numeric,
  rental_price numeric,
  image_url text,
  available_quantity integer DEFAULT 0,
  total_quantity integer DEFAULT 0,
  rating numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pack text,
  min_age integer,
  max_age integer,
  show_strikethrough_pricing boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 9999,
  is_featured boolean NOT NULL DEFAULT false,
  subscription_category USER-DEFINED DEFAULT 'educational_toys'::subscription_category,
  sku text,
  reorder_level integer DEFAULT 5,
  reorder_quantity integer DEFAULT 10,
  supplier_id uuid,
  purchase_cost numeric,
  last_restocked_date date,
  inventory_status text DEFAULT 'active'::text CHECK (inventory_status = ANY (ARRAY['active'::text, 'discontinued'::text, 'seasonal'::text, 'maintenance'::text])),
  weight_kg numeric,
  dimensions_cm text,
  barcode text UNIQUE,
  internal_notes text,
  seasonal_availability jsonb DEFAULT '{}'::jsonb,
  condition_rating integer DEFAULT 5 CHECK (condition_rating >= 1 AND condition_rating <= 5),
  maintenance_required boolean DEFAULT false,
  last_maintenance_date date,
  CONSTRAINT toys_pkey PRIMARY KEY (id),
  CONSTRAINT fk_toys_supplier FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.toys_1_2_years (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_toy_id uuid UNIQUE,
  name text NOT NULL,
  brand text,
  category text,
  age_range text,
  retail_price numeric,
  rental_price numeric,
  image_url text,
  description text,
  available_quantity integer DEFAULT 0,
  total_quantity integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT toys_1_2_years_pkey PRIMARY KEY (id),
  CONSTRAINT toys_1_2_years_original_toy_id_fkey FOREIGN KEY (original_toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.toys_2_3_years (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_toy_id uuid UNIQUE,
  name text NOT NULL,
  brand text,
  category text,
  age_range text,
  retail_price numeric,
  rental_price numeric,
  image_url text,
  description text,
  available_quantity integer DEFAULT 0,
  total_quantity integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT toys_2_3_years_pkey PRIMARY KEY (id),
  CONSTRAINT toys_2_3_years_original_toy_id_fkey FOREIGN KEY (original_toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.toys_3_4_years (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_toy_id uuid UNIQUE,
  name text NOT NULL,
  brand text,
  category text,
  age_range text,
  retail_price numeric,
  rental_price numeric,
  image_url text,
  description text,
  available_quantity integer DEFAULT 0,
  total_quantity integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT toys_3_4_years_pkey PRIMARY KEY (id),
  CONSTRAINT toys_3_4_years_original_toy_id_fkey FOREIGN KEY (original_toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.toys_4_6_years (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_toy_id uuid UNIQUE,
  name text NOT NULL,
  brand text,
  category text,
  age_range text,
  retail_price numeric,
  rental_price numeric,
  image_url text,
  description text,
  available_quantity integer DEFAULT 0,
  total_quantity integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT toys_4_6_years_pkey PRIMARY KEY (id),
  CONSTRAINT toys_4_6_years_original_toy_id_fkey FOREIGN KEY (original_toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.toys_6_8_years (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  original_toy_id uuid UNIQUE,
  name text NOT NULL,
  brand text,
  category text,
  age_range text,
  retail_price numeric,
  rental_price numeric,
  image_url text,
  description text,
  available_quantity integer DEFAULT 0,
  total_quantity integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT toys_6_8_years_pkey PRIMARY KEY (id),
  CONSTRAINT toys_6_8_years_original_toy_id_fkey FOREIGN KEY (original_toy_id) REFERENCES public.toys(id)
);
CREATE TABLE public.user_entitlements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subscription_id uuid NOT NULL,
  current_month timestamp with time zone NOT NULL DEFAULT now(),
  standard_toys_remaining integer NOT NULL DEFAULT 0,
  big_toys_remaining integer NOT NULL DEFAULT 0,
  books_remaining integer NOT NULL DEFAULT 0,
  premium_toys_remaining integer DEFAULT 0,
  value_cap_remaining numeric NOT NULL DEFAULT 0,
  early_access boolean NOT NULL DEFAULT false,
  reservation_enabled boolean NOT NULL DEFAULT false,
  roller_coaster_delivered boolean NOT NULL DEFAULT false,
  coupe_ride_delivered boolean NOT NULL DEFAULT false,
  next_billing_date timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  toys_in_possession boolean DEFAULT false,
  current_cycle_toys jsonb DEFAULT '[]'::jsonb,
  selection_window_active boolean DEFAULT false,
  CONSTRAINT user_entitlements_pkey PRIMARY KEY (id),
  CONSTRAINT user_entitlements_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.user_journey_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  session_id text NOT NULL,
  event_type text NOT NULL,
  event_data jsonb,
  page_url text,
  timestamp timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_journey_events_pkey PRIMARY KEY (id),
  CONSTRAINT user_journey_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.user_lifecycle_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['created'::text, 'activated'::text, 'deactivated'::text, 'suspended'::text, 'verified'::text, 'role_assigned'::text, 'role_removed'::text, 'password_reset'::text, 'profile_updated'::text, 'subscription_changed'::text, 'promotion_applied'::text, 'status_changed'::text])),
  previous_state jsonb,
  new_state jsonb,
  performed_by uuid,
  reason text CHECK (length(reason) <= 500),
  notes text CHECK (length(notes) <= 2000),
  ip_address inet,
  user_agent text,
  session_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_lifecycle_events_pkey PRIMARY KEY (id),
  CONSTRAINT user_lifecycle_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT user_lifecycle_events_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.user_offer_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  offer_id uuid NOT NULL,
  assigned_by uuid NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  used_at timestamp with time zone,
  is_used boolean DEFAULT false,
  order_id uuid,
  notes text,
  expires_at timestamp with time zone,
  CONSTRAINT user_offer_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT user_offer_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT user_offer_assignments_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.promotional_offers(id),
  CONSTRAINT user_offer_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.user_permission_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE CHECK (length(name) >= 2 AND length(name) <= 50),
  display_name text NOT NULL CHECK (length(display_name) >= 2 AND length(display_name) <= 100),
  description text,
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(permissions) = 'object'::text),
  is_system_role boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT user_permission_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_permission_roles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.user_role_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  assigned_by uuid,
  assigned_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  notes text CHECK (length(notes) <= 1000),
  CONSTRAINT user_role_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT user_role_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id),
  CONSTRAINT user_role_assignments_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.user_permission_roles(id),
  CONSTRAINT user_role_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.custom_users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  refresh_token text NOT NULL UNIQUE,
  device_info jsonb,
  ip_address inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL,
  refresh_expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_used timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.user_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  plan_type text NOT NULL CHECK (plan_type = ANY (ARRAY['trial'::text, 'basic'::text, 'standard'::text, 'premium'::text, 'enterprise'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'cancelled'::text, 'expired'::text, 'pending'::text, 'suspended'::text])),
  current_period_start timestamp with time zone NOT NULL,
  current_period_end timestamp with time zone NOT NULL,
  billing_cycle text NOT NULL CHECK (billing_cycle = ANY (ARRAY['monthly'::text, 'quarterly'::text, 'semi-annual'::text, 'annual'::text])),
  auto_renewal boolean DEFAULT true,
  base_amount numeric NOT NULL,
  discount_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  payment_method text CHECK (payment_method = ANY (ARRAY['card'::text, 'upi'::text, 'net_banking'::text, 'wallet'::text, 'cash'::text])),
  next_billing_date timestamp with time zone,
  grace_period_end timestamp with time zone,
  pause_count integer DEFAULT 0,
  extension_days integer DEFAULT 0,
  free_months_added integer DEFAULT 0,
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  extensions_used_this_period integer DEFAULT 0,
  max_extensions_per_period integer DEFAULT 3,
  CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.custom_users(id)
);
CREATE TABLE public.wishlist (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  toy_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wishlist_pkey PRIMARY KEY (id),
  CONSTRAINT wishlist_toy_id_fkey FOREIGN KEY (toy_id) REFERENCES public.toys(id),
  CONSTRAINT wishlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);