// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Production Supabase configuration - connect directly to production
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://wucwpyitzqjukcphczhr.supabase.co";
// New Supabase publishable key (replaces legacy anon JWT)
const PRODUCTION_ANON_KEY = "sb_publishable_FSkXrLtW_fYLLGipAoq1Hw_ltq5Ij-J";
const envKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
// Only use env key if it's the new sb_publishable_ format; legacy JWTs are disabled
const SUPABASE_PUBLISHABLE_KEY =
  (typeof envKey === "string" && envKey.startsWith("sb_publishable_"))
    ? envKey
    : PRODUCTION_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
  },
});